const EDITOR_REASON_CODES = Object.freeze({
  EDITOR_APPROVED: "EDITOR_APPROVED",
  EDITOR_REPAIRED: "EDITOR_REPAIRED",
  EDITOR_BLOCKED: "EDITOR_BLOCKED",
  EDITOR_TIMEOUT: "EDITOR_TIMEOUT",
  EDITOR_NUMERIC_MISMATCH: "EDITOR_NUMERIC_MISMATCH",
  EDITOR_ENTITY_MISMATCH: "EDITOR_ENTITY_MISMATCH",
  EDITOR_ROLE_MISMATCH: "EDITOR_ROLE_MISMATCH",
  EDITOR_ATTRIBUTION_MISMATCH: "EDITOR_ATTRIBUTION_MISMATCH",
  EDITOR_QUOTE_MISMATCH: "EDITOR_QUOTE_MISMATCH",
  EDITOR_UNCERTAINTY_UPGRADED: "EDITOR_UNCERTAINTY_UPGRADED",
  EDITOR_HEADLINE_BODY_MISMATCH: "EDITOR_HEADLINE_BODY_MISMATCH",
  EDITOR_LANGUAGE_INVALID: "EDITOR_LANGUAGE_INVALID",
  EDITOR_UNSUPPORTED_CLAIM: "EDITOR_UNSUPPORTED_CLAIM",
  EDITOR_SOURCE_EVIDENCE_INSUFFICIENT: "EDITOR_SOURCE_EVIDENCE_INSUFFICIENT",
});

const ISSUE_CODES = Object.freeze({
  NUMERIC_MISMATCH: "NUMERIC_MISMATCH",
  ENTITY_MISMATCH: "ENTITY_MISMATCH",
  ROLE_MISMATCH: "ROLE_MISMATCH",
  ATTRIBUTION_MISMATCH: "ATTRIBUTION_MISMATCH",
  QUOTE_MISMATCH: "QUOTE_MISMATCH",
  UNCERTAINTY_UPGRADED: "UNCERTAINTY_UPGRADED",
  HEADLINE_BODY_MISMATCH: "HEADLINE_BODY_MISMATCH",
  LANGUAGE_INVALID: "LANGUAGE_INVALID",
  UNSUPPORTED_CLAIM: "UNSUPPORTED_CLAIM",
  SOURCE_EVIDENCE_INSUFFICIENT: "SOURCE_EVIDENCE_INSUFFICIENT",
  MALFORMED_OUTPUT: "MALFORMED_OUTPUT",
  DUPLICATE_HEADLINE: "DUPLICATE_HEADLINE",
});

module.exports = {
  EDITOR_REASON_CODES,
  ISSUE_CODES,
};
