const EDITORIAL_EVENTS = {
  US_FED_RATE_DECISION: {
    canonicalEventKey: "US_FED_RATE_DECISION",
    displayName: "Federal Reserve Interest Rate Decision",
    category: "central_bank",
    country: "US",
    institution: "FEDERAL_RESERVE",
    defaultPerson: null,
    primaryVisualSubjects: [
      "Federal Reserve Eccles Building exterior as primary subject",
      "FOMC boardroom or official policy-decision atmosphere",
      "recognizable US central bank institutional architecture",
    ],
    secondaryVisualSubjects: ["subtle US Treasury market context", "subtle US dollar market context"],
    affectedMarkets: ["USD", "US_TREASURIES", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "natural institutional daylight or restrained conference lighting",
    mood: "measured policy authority",
    forbiddenElements: ["anonymous shadow boardroom crowd as main subject", "generic movie poster atmosphere", "Jerome Powell unless press conference context"],
    overlayPlacement: "overlay-top-left",
    personPolicy: "institution_primary",
  },
  US_FED_STATEMENT: {
    canonicalEventKey: "US_FED_STATEMENT",
    displayName: "FOMC Statement",
    category: "central_bank",
    country: "US",
    institution: "FEDERAL_RESERVE",
    primaryVisualSubjects: ["FOMC statement release atmosphere", "Federal Reserve briefing room", "policy document moment without readable text"],
    secondaryVisualSubjects: ["US Treasury context", "US dollar context"],
    affectedMarkets: ["USD", "US_TREASURIES", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "professional briefing lighting",
    mood: "official policy communication",
    forbiddenElements: ["unrelated press podium as sole subject"],
    overlayPlacement: "overlay-top-left",
    personPolicy: "institution_primary",
  },
  US_POWELL_SPEECH: {
    canonicalEventKey: "US_POWELL_SPEECH",
    displayName: "Federal Reserve Press Conference",
    category: "central_bank_speech",
    country: "US",
    institution: "FEDERAL_RESERVE",
    defaultPerson: "JEROME_POWELL",
    primaryVisualSubjects: [
      "Jerome Powell as primary subject at Federal Reserve press briefing",
      "podium and microphones in professional policy environment",
      "Federal Reserve press conference room",
    ],
    secondaryVisualSubjects: ["subtle Federal Reserve institutional backdrop", "professional press environment"],
    affectedMarkets: ["USD", "US_TREASURIES", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "realistic press briefing lighting",
    mood: "credible central bank communication",
    forbiddenElements: ["unrelated boardroom crowd", "generic silhouettes"],
    overlayPlacement: "overlay-top-left",
    personPolicy: "person_primary",
  },
  US_FOMC_MINUTES: {
    canonicalEventKey: "US_FOMC_MINUTES",
    displayName: "FOMC Minutes",
    category: "central_bank",
    country: "US",
    institution: "FEDERAL_RESERVE",
    primaryVisualSubjects: ["Federal Reserve policy archive atmosphere", "FOMC meeting room context"],
    secondaryVisualSubjects: ["policy documents without readable text"],
    affectedMarkets: ["USD", "US_TREASURIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "institutional office lighting",
    mood: "policy review",
    forbiddenElements: [],
    overlayPlacement: "overlay-top-left",
    personPolicy: "institution_primary",
  },
  US_BEIGE_BOOK: {
    canonicalEventKey: "US_BEIGE_BOOK",
    displayName: "Fed Beige Book",
    category: "central_bank",
    country: "US",
    institution: "FEDERAL_RESERVE",
    primaryVisualSubjects: ["regional US economy research atmosphere", "Federal Reserve district economic context"],
    secondaryVisualSubjects: ["US commerce and business districts"],
    affectedMarkets: ["USD", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "natural professional lighting",
    mood: "regional economic survey",
    forbiddenElements: [],
    overlayPlacement: "overlay-top-left",
    personPolicy: "institution_primary",
  },
  US_JACKSON_HOLE: {
    canonicalEventKey: "US_JACKSON_HOLE",
    displayName: "Jackson Hole Symposium",
    category: "central_bank",
    country: "US",
    institution: "FEDERAL_RESERVE",
    primaryVisualSubjects: ["Jackson Hole economic symposium atmosphere", "central banking conference setting in mountain resort context"],
    secondaryVisualSubjects: ["global central bank policy context"],
    affectedMarkets: ["USD", "US_TREASURIES", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "natural conference lighting",
    mood: "global policy forum",
    forbiddenElements: ["fantasy mountain scene"],
    overlayPlacement: "overlay-top-left",
    personPolicy: "institution_primary",
  },
  US_CPI_MOM: {
    canonicalEventKey: "US_CPI_MOM",
    displayName: "US Consumer Price Index",
    category: "inflation",
    country: "US",
    institution: "US_BLS",
    primaryVisualSubjects: [
      "US inflation and consumer-price scene",
      "recognizable consumer goods and shopping context",
      "supermarket or retail consumer basket environment",
    ],
    secondaryVisualSubjects: ["subtle US macroeconomic environment", "sophisticated market reaction elements without readable numbers"],
    affectedMarkets: ["USD", "US_TREASURIES", "GOLD", "EQUITIES"],
    compositionPreference: "overlay-lower-center",
    lightingPreference: "natural retail and newsroom lighting",
    mood: "consumer inflation focus",
    forbiddenElements: ["plain chart-only background", "readable price tags"],
    overlayPlacement: "overlay-lower-center",
    personPolicy: "none",
  },
  US_CPI_YOY: { extends: "US_CPI_MOM", canonicalEventKey: "US_CPI_YOY" },
  US_CPI_GENERIC: { extends: "US_CPI_MOM", canonicalEventKey: "US_CPI_GENERIC" },
  US_CORE_CPI_MOM: {
    extends: "US_CPI_MOM",
    canonicalEventKey: "US_CORE_CPI_MOM",
    displayName: "US Core CPI",
    primaryVisualSubjects: ["core inflation and underlying consumer price context", "essential goods and services consumer environment"],
  },
  US_CORE_CPI_YOY: { extends: "US_CORE_CPI_MOM", canonicalEventKey: "US_CORE_CPI_YOY" },
  US_PPI_MOM: {
    canonicalEventKey: "US_PPI_MOM",
    displayName: "US Producer Price Index",
    category: "inflation",
    country: "US",
    institution: "US_BEA",
    primaryVisualSubjects: ["producer price and wholesale inflation scene", "factory inputs and supply chain pricing context"],
    secondaryVisualSubjects: ["industrial goods environment"],
    affectedMarkets: ["USD", "US_TREASURIES", "EQUITIES"],
    compositionPreference: "overlay-lower-center",
    lightingPreference: "industrial and newsroom lighting",
    mood: "producer inflation",
    forbiddenElements: ["readable wholesale price labels"],
    overlayPlacement: "overlay-lower-center",
    personPolicy: "none",
  },
  US_PPI_YOY: { extends: "US_PPI_MOM", canonicalEventKey: "US_PPI_YOY" },
  US_CORE_PCE_MOM: {
    canonicalEventKey: "US_CORE_PCE_MOM",
    displayName: "US Core PCE",
    category: "inflation",
    country: "US",
    institution: "US_BEA",
    primaryVisualSubjects: ["personal consumption and inflation context", "consumer spending environment"],
    secondaryVisualSubjects: ["subtle Fed policy relevance without central bank building as sole subject"],
    affectedMarkets: ["USD", "US_TREASURIES", "GOLD"],
    compositionPreference: "overlay-lower-center",
    lightingPreference: "natural consumer environment lighting",
    mood: "core inflation measure",
    forbiddenElements: [],
    overlayPlacement: "overlay-lower-center",
    personPolicy: "none",
  },
  US_CORE_PCE_YOY: { extends: "US_CORE_PCE_MOM", canonicalEventKey: "US_CORE_PCE_YOY" },
  US_NFP: {
    canonicalEventKey: "US_NFP",
    displayName: "Non Farm Payrolls",
    category: "labor",
    country: "US",
    institution: "US_BLS",
    primaryVisualSubjects: [
      "US employment and labor-market scene",
      "modern offices and hiring environment",
      "workers and business city context",
    ],
    secondaryVisualSubjects: ["subtle employment data visualization without numbers", "professional workforce editorial scene"],
    affectedMarkets: ["USD", "US_TREASURIES", "EQUITIES", "GOLD"],
    compositionPreference: "overlay-lower-left",
    lightingPreference: "natural office and city daylight",
    mood: "labor market release",
    forbiddenElements: ["generic dark silhouettes in a room", "depressing imagery"],
    overlayPlacement: "overlay-lower-left",
    personPolicy: "none",
  },
  US_UNEMPLOYMENT_RATE: {
    extends: "US_NFP",
    canonicalEventKey: "US_UNEMPLOYMENT_RATE",
    displayName: "US Unemployment Rate",
    primaryVisualSubjects: ["US unemployment and workforce transition scene", "job search and labor office context"],
  },
  US_ADP: { extends: "US_NFP", canonicalEventKey: "US_ADP", institution: "ADP", displayName: "ADP Employment Report" },
  US_ADP_EMPLOYMENT: { extends: "US_NFP", canonicalEventKey: "US_ADP_EMPLOYMENT", institution: "ADP" },
  US_INITIAL_JOBLESS_CLAIMS: {
    canonicalEventKey: "US_INITIAL_JOBLESS_CLAIMS",
    displayName: "Initial Jobless Claims",
    category: "labor",
    country: "US",
    institution: "US_DOL",
    primaryVisualSubjects: [
      "labor office and employment filing environment",
      "workforce transition and claims processing context",
      "human and institutional labor-market context",
    ],
    secondaryVisualSubjects: ["professional government workforce services setting"],
    affectedMarkets: ["USD", "US_TREASURIES", "EQUITIES"],
    compositionPreference: "overlay-lower-left",
    lightingPreference: "natural office lighting",
    mood: "measured labor transition",
    forbiddenElements: ["sensational unemployment imagery", "dark despair tone"],
    overlayPlacement: "overlay-lower-left",
    personPolicy: "none",
  },
  US_CONTINUING_JOBLESS_CLAIMS: { extends: "US_INITIAL_JOBLESS_CLAIMS", canonicalEventKey: "US_CONTINUING_JOBLESS_CLAIMS", displayName: "Continuing Jobless Claims" },
  US_GDP_QOQ: {
    canonicalEventKey: "US_GDP_QOQ",
    displayName: "US GDP",
    category: "growth",
    country: "US",
    institution: "US_BEA",
    primaryVisualSubjects: ["broad US economy and commerce scene", "infrastructure and business activity", "national output and growth context"],
    secondaryVisualSubjects: ["ports logistics and urban commerce"],
    affectedMarkets: ["USD", "US_TREASURIES", "EQUITIES"],
    compositionPreference: "overlay-lower-center",
    lightingPreference: "natural daylight over US commerce",
    mood: "macro growth",
    forbiddenElements: [],
    overlayPlacement: "overlay-lower-center",
    personPolicy: "none",
  },
  US_RETAIL_SALES: {
    extends: "US_GDP_QOQ",
    canonicalEventKey: "US_RETAIL_SALES",
    displayName: "US Retail Sales",
    primaryVisualSubjects: ["US retail stores and consumer spending scene", "shopping districts and commerce activity"],
    affectedMarkets: ["USD", "EQUITIES"],
  },
  US_CONSUMER_CONFIDENCE: {
    extends: "US_GDP_QOQ",
    canonicalEventKey: "US_CONSUMER_CONFIDENCE",
    displayName: "US Consumer Confidence",
    primaryVisualSubjects: ["US consumer sentiment and household spending context", "shopping and household economy scene"],
  },
  US_MICHIGAN_SENTIMENT: {
    extends: "US_GDP_QOQ",
    canonicalEventKey: "US_MICHIGAN_SENTIMENT",
    displayName: "Michigan Consumer Sentiment",
    primaryVisualSubjects: ["US household sentiment and consumer outlook context"],
  },
  US_ISM_MANUFACTURING: {
    canonicalEventKey: "US_ISM_MANUFACTURING",
    displayName: "ISM Manufacturing",
    category: "business_activity",
    country: "US",
    institution: "ISM",
    primaryVisualSubjects: ["active modern factory and production floor", "manufacturing logistics and supply chain"],
    secondaryVisualSubjects: ["business activity dashboard elements without readable numbers"],
    affectedMarkets: ["USD", "EQUITIES"],
    compositionPreference: "overlay-lower-left",
    lightingPreference: "industrial natural lighting",
    mood: "manufacturing activity",
    forbiddenElements: ["empty warehouse only"],
    overlayPlacement: "overlay-lower-left",
    personPolicy: "none",
  },
  US_ISM_SERVICES: {
    extends: "US_ISM_MANUFACTURING",
    canonicalEventKey: "US_ISM_SERVICES",
    displayName: "ISM Services",
    primaryVisualSubjects: ["services sector business activity", "modern office services and logistics environment"],
    institution: "ISM",
  },
  US_PMI_MANUFACTURING: { extends: "US_ISM_MANUFACTURING", canonicalEventKey: "US_PMI_MANUFACTURING", displayName: "US Manufacturing PMI" },
  US_PMI_SERVICES: { extends: "US_ISM_SERVICES", canonicalEventKey: "US_PMI_SERVICES", displayName: "US Services PMI" },
  ECB_RATE_DECISION: {
    canonicalEventKey: "ECB_RATE_DECISION",
    displayName: "ECB Interest Rate Decision",
    category: "central_bank",
    country: "EUROZONE",
    institution: "ECB",
    primaryVisualSubjects: ["ECB headquarters Frankfurt as primary subject", "euro-area monetary policy decision atmosphere"],
    secondaryVisualSubjects: ["euro currency context", "European bond market context"],
    affectedMarkets: ["EUR", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "modern European institutional lighting",
    mood: "euro-area policy authority",
    forbiddenElements: ["Federal Reserve architecture", "US dollar primary symbolism"],
    overlayPlacement: "overlay-top-left",
    personPolicy: "institution_primary",
  },
  ECB_LAGARDE_SPEECH: {
    canonicalEventKey: "ECB_LAGARDE_SPEECH",
    displayName: "ECB Press Conference",
    category: "central_bank_speech",
    country: "EUROZONE",
    institution: "ECB",
    defaultPerson: "CHRISTINE_LAGARDE",
    primaryVisualSubjects: ["Christine Lagarde as primary subject at ECB press briefing", "European central bank press conference environment"],
    secondaryVisualSubjects: ["ECB institutional backdrop"],
    affectedMarkets: ["EUR", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "professional press briefing lighting",
    mood: "ECB communication",
    forbiddenElements: ["Federal Reserve building"],
    overlayPlacement: "overlay-top-left",
    personPolicy: "person_primary",
  },
  BOE_RATE_DECISION: {
    canonicalEventKey: "BOE_RATE_DECISION",
    displayName: "Bank of England Rate Decision",
    category: "central_bank",
    country: "UK",
    institution: "BANK_OF_ENGLAND",
    primaryVisualSubjects: ["Bank of England headquarters as primary subject", "UK monetary policy decision atmosphere"],
    secondaryVisualSubjects: ["British pound context", "UK gilt market context"],
    affectedMarkets: ["GBP", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "historic institutional lighting",
    mood: "UK policy authority",
    forbiddenElements: ["Federal Reserve", "ECB tower"],
    overlayPlacement: "overlay-top-left",
    personPolicy: "institution_primary",
  },
  BOE_BAILEY_SPEECH: {
    canonicalEventKey: "BOE_BAILEY_SPEECH",
    displayName: "Bank of England Press Conference",
    category: "central_bank_speech",
    country: "UK",
    institution: "BANK_OF_ENGLAND",
    defaultPerson: "ANDREW_BAILEY",
    primaryVisualSubjects: ["Andrew Bailey as primary subject at Bank of England press briefing"],
    secondaryVisualSubjects: ["Bank of England institutional backdrop"],
    affectedMarkets: ["GBP", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "professional briefing lighting",
    mood: "BoE communication",
    forbiddenElements: ["Federal Reserve"],
    overlayPlacement: "overlay-top-left",
    personPolicy: "person_primary",
  },
  BOJ_RATE_DECISION: {
    canonicalEventKey: "BOJ_RATE_DECISION",
    displayName: "Bank of Japan Rate Decision",
    category: "central_bank",
    country: "JP",
    institution: "BANK_OF_JAPAN",
    primaryVisualSubjects: ["Bank of Japan headquarters Tokyo as primary subject", "Japanese monetary policy decision atmosphere"],
    secondaryVisualSubjects: ["Japanese yen context", "JGB market context"],
    affectedMarkets: ["JPY", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "Tokyo institutional lighting",
    mood: "BoJ policy authority",
    forbiddenElements: ["Federal Reserve architecture"],
    overlayPlacement: "overlay-top-left",
    personPolicy: "institution_primary",
  },
  BOJ_UEDA_SPEECH: {
    canonicalEventKey: "BOJ_UEDA_SPEECH",
    displayName: "Bank of Japan Press Conference",
    category: "central_bank_speech",
    country: "JP",
    institution: "BANK_OF_JAPAN",
    defaultPerson: "KAZUO_UEDA",
    primaryVisualSubjects: ["Kazuo Ueda as primary subject at Bank of Japan press briefing"],
    secondaryVisualSubjects: ["Bank of Japan institutional backdrop"],
    affectedMarkets: ["JPY", "EQUITIES"],
    compositionPreference: "overlay-top-left",
    lightingPreference: "professional briefing lighting",
    mood: "BoJ communication",
    forbiddenElements: ["Federal Reserve"],
    overlayPlacement: "overlay-top-left",
    personPolicy: "person_primary",
  },
};

function resolveEventDefinition(eventKey) {
  const key = String(eventKey || "").trim().toUpperCase();
  const raw = EDITORIAL_EVENTS[key];
  if (!raw) {
    return null;
  }
  if (raw.extends) {
    const base = resolveEventDefinition(raw.extends);
    return { ...base, ...raw, canonicalEventKey: raw.canonicalEventKey || key };
  }
  return { ...raw, canonicalEventKey: raw.canonicalEventKey || key };
}

function listEditorialEventKeys() {
  return Object.keys(EDITORIAL_EVENTS);
}

module.exports = {
  EDITORIAL_EVENTS,
  resolveEventDefinition,
  listEditorialEventKeys,
};
