const INSTITUTIONS = {
  FEDERAL_RESERVE: {
    id: "FEDERAL_RESERVE",
    names: ["Federal Reserve", "Fed", "FOMC", "US central bank"],
    aliases: ["federal reserve system", "the fed"],
    country: "US",
    institutionType: "central_bank",
    visualSubjects: ["Federal Reserve Eccles Building exterior", "FOMC boardroom", "monetary policy briefing room"],
    architectureHints: ["neoclassical Federal Reserve headquarters", "Washington DC institutional architecture"],
    symbolicElements: ["US Treasury market context", "US dollar market context", "policy documents without readable text"],
    forbiddenMisrepresentations: ["European central bank architecture", "generic parliament building"],
  },
  ECB: {
    id: "ECB",
    names: ["European Central Bank", "ECB"],
    aliases: ["euro central bank"],
    country: "EUROZONE",
    institutionType: "central_bank",
    visualSubjects: ["ECB headquarters Frankfurt", "euro-area policy briefing room"],
    architectureHints: ["modern European central bank tower", "Frankfurt financial district"],
    symbolicElements: ["euro currency context", "European government bond market"],
    forbiddenMisrepresentations: ["Federal Reserve building", "Bank of England"],
  },
  BANK_OF_ENGLAND: {
    id: "BANK_OF_ENGLAND",
    names: ["Bank of England", "BoE"],
    aliases: ["boe", "uk central bank"],
    country: "UK",
    institutionType: "central_bank",
    visualSubjects: ["Bank of England headquarters", "UK monetary policy briefing"],
    architectureHints: ["historic London central bank architecture"],
    symbolicElements: ["British pound market context", "UK gilt market context"],
    forbiddenMisrepresentations: ["Federal Reserve", "ECB tower"],
  },
  BANK_OF_JAPAN: {
    id: "BANK_OF_JAPAN",
    names: ["Bank of Japan", "BoJ"],
    aliases: ["boj", "japan central bank"],
    country: "JP",
    institutionType: "central_bank",
    visualSubjects: ["Bank of Japan headquarters Tokyo", "Japanese monetary policy briefing"],
    architectureHints: ["Tokyo central bank institutional building"],
    symbolicElements: ["Japanese yen market context", "JGB bond market context"],
    forbiddenMisrepresentations: ["Federal Reserve", "ECB"],
  },
  US_BLS: {
    id: "US_BLS",
    names: ["Bureau of Labor Statistics", "BLS", "US Department of Labor statistics"],
    aliases: ["labor statistics bureau"],
    country: "US",
    institutionType: "statistics_agency",
    visualSubjects: ["US labor statistics release environment", "employment report newsroom"],
    architectureHints: ["professional US government data release setting"],
    symbolicElements: ["employment data visualization without numbers"],
    forbiddenMisrepresentations: ["central bank boardroom as primary"],
  },
  US_BEA: {
    id: "US_BEA",
    names: ["Bureau of Economic Analysis", "BEA"],
    country: "US",
    institutionType: "statistics_agency",
    visualSubjects: ["US economic statistics release room", "macro data briefing environment"],
    architectureHints: ["clean institutional data release setting"],
    symbolicElements: ["national accounts context without readable numbers"],
    forbiddenMisrepresentations: [],
  },
  US_DOL: {
    id: "US_DOL",
    names: ["US Department of Labor", "Department of Labor"],
    country: "US",
    institutionType: "government_agency",
    visualSubjects: ["US labor department environment", "workforce policy setting"],
    architectureHints: ["professional government office"],
    symbolicElements: ["employment services context"],
    forbiddenMisrepresentations: [],
  },
  ISM: {
    id: "ISM",
    names: ["ISM", "Institute for Supply Management"],
    country: "US",
    institutionType: "business_survey",
    visualSubjects: ["US manufacturing survey release environment", "business activity briefing"],
    architectureHints: ["professional business survey newsroom"],
    symbolicElements: ["factory and services activity context"],
    forbiddenMisrepresentations: [],
  },
  ADP: {
    id: "ADP",
    names: ["ADP", "ADP Employment"],
    country: "US",
    institutionType: "private_survey",
    visualSubjects: ["private payroll survey release environment", "US hiring analytics setting"],
    architectureHints: ["modern payroll analytics office"],
    symbolicElements: ["employment hiring context"],
    forbiddenMisrepresentations: ["central bank primary scene"],
  },
};

module.exports = { INSTITUTIONS };
