const PEOPLE = {
  JEROME_POWELL: {
    id: "JEROME_POWELL",
    names: ["Jerome Powell", "Jay Powell", "Powell"],
    aliases: ["fed chair powell", "chair powell", "federal reserve chair"],
    institution: "FEDERAL_RESERVE",
    country: "US",
    role: "Federal Reserve Chair",
    visualDescription: "Jerome Powell, Federal Reserve Chair, professional press briefing appearance",
    allowedContexts: ["US_POWELL_SPEECH", "US_FED_RATE_DECISION", "US_FED_STATEMENT", "US_FOMC_MINUTES"],
    portraitPolicy: "primary_only_for_speech_or_direct_statement",
  },
  CHRISTINE_LAGARDE: {
    id: "CHRISTINE_LAGARDE",
    names: ["Christine Lagarde", "Lagarde"],
    aliases: ["ecb president lagarde", "president lagarde"],
    institution: "ECB",
    country: "EUROZONE",
    role: "ECB President",
    visualDescription: "Christine Lagarde, ECB President, European central bank press briefing",
    allowedContexts: ["ECB_LAGARDE_SPEECH", "ECB_RATE_DECISION"],
    portraitPolicy: "primary_only_for_speech",
  },
  ANDREW_BAILEY: {
    id: "ANDREW_BAILEY",
    names: ["Andrew Bailey", "Bailey"],
    aliases: ["boe governor bailey", "governor bailey"],
    institution: "BANK_OF_ENGLAND",
    country: "UK",
    role: "Bank of England Governor",
    visualDescription: "Andrew Bailey, Bank of England Governor, institutional press setting",
    allowedContexts: ["BOE_BAILEY_SPEECH", "BOE_RATE_DECISION"],
    portraitPolicy: "primary_only_for_speech",
  },
  KAZUO_UEDA: {
    id: "KAZUO_UEDA",
    names: ["Kazuo Ueda", "Ueda"],
    aliases: ["boj governor ueda", "governor ueda"],
    institution: "BANK_OF_JAPAN",
    country: "JP",
    role: "Bank of Japan Governor",
    visualDescription: "Kazuo Ueda, Bank of Japan Governor, Tokyo institutional briefing",
    allowedContexts: ["BOJ_UEDA_SPEECH", "BOJ_RATE_DECISION"],
    portraitPolicy: "primary_only_for_speech",
  },
  PHILIP_JEFFERSON: {
    id: "PHILIP_JEFFERSON",
    names: ["Philip Jefferson", "Jefferson"],
    institution: "FEDERAL_RESERVE",
    country: "US",
    role: "Federal Reserve Vice Chair",
    visualDescription: "Federal Reserve official in institutional setting",
    allowedContexts: ["US_POWELL_SPEECH"],
    portraitPolicy: "secondary_only",
  },
  CHRISTOPHER_WALLER: {
    id: "CHRISTOPHER_WALLER",
    names: ["Christopher Waller", "Waller"],
    institution: "FEDERAL_RESERVE",
    country: "US",
    role: "Federal Reserve Governor",
    visualDescription: "Federal Reserve official in policy setting",
    allowedContexts: [],
    portraitPolicy: "mention_only",
  },
  MICHELLE_BOWMAN: {
    id: "MICHELLE_BOWMAN",
    names: ["Michelle Bowman", "Bowman"],
    institution: "FEDERAL_RESERVE",
    country: "US",
    role: "Federal Reserve Governor",
    visualDescription: "Federal Reserve official in policy setting",
    allowedContexts: [],
    portraitPolicy: "mention_only",
  },
  JOHN_WILLIAMS: {
    id: "JOHN_WILLIAMS",
    names: ["John Williams", "Williams"],
    institution: "FEDERAL_RESERVE",
    country: "US",
    role: "New York Fed President",
    visualDescription: "Federal Reserve regional president in institutional setting",
    allowedContexts: [],
    portraitPolicy: "mention_only",
  },
  MARY_DALY: {
    id: "MARY_DALY",
    names: ["Mary Daly", "Daly"],
    institution: "FEDERAL_RESERVE",
    country: "US",
    role: "San Francisco Fed President",
    visualDescription: "Federal Reserve regional president in institutional setting",
    allowedContexts: [],
    portraitPolicy: "mention_only",
  },
};

module.exports = { PEOPLE };
