const REALISM_DIRECTIVES = [
  "premium financial editorial photography",
  "realistic newsroom lighting",
  "credible institutional setting",
  "restrained dramatic lighting",
  "natural professional atmosphere",
  "modern financial publication cover quality",
  "photorealistic editorial photography",
  "physically plausible people and scenes",
  "clean professional composition",
  "visually legible on mobile",
].join(", ");

const TEXT_FREE_DIRECTIVE = [
  "absolutely no text",
  "no letters",
  "no words",
  "no captions",
  "no headlines",
  "no typography",
  "no numbers",
  "no labels",
  "no readable signs",
  "no readable screens",
  "no written reports",
  "no printed documents facing the camera",
  "no posters",
  "no banners",
  "no newspaper headlines",
  "all screens must be abstract and unreadable",
].join(", ");

const NEGATIVE_PROMPT = [
  TEXT_FREE_DIRECTIVE,
  "no logos",
  "no watermarks",
  "no fake seals",
  "no fake government emblems",
  "no deformed hands",
  "no distorted faces",
  "no anonymous shadow silhouettes as main subjects",
  "no dark cinematic movie-poster look",
  "no fantasy architecture",
  "no surreal objects",
  "no generic glowing line chart as primary subject",
  "no clutter",
  "no excessive darkness",
  "no oversaturated gold",
  "no low-detail faces",
  "no duplicated people",
  "no gradient-only background",
  "no grid-only background",
  "no simple geometric icons as main subject",
  "no empty text card",
  "not a digital painting",
  "not surreal",
  "not a movie poster",
  "not a generic stock illustration",
].join(", ");

const FORBIDDEN_PROMPT_TERMS = [
  "Bloomberg",
  "Reuters",
  "CNBC",
  "Previous",
  "Forecast",
  "Actual",
  "Hasan",
  "Chart World",
  "hasanchart",
  "t.me",
  "http",
  "high-stakes dramatic movie scene",
  "extreme cinematic tension",
  "dark mysterious boardroom",
  "epic glowing chart",
];

const OVERLAY_PLACEMENTS = {
  "overlay-top-left": "leave clean negative space in the upper-left quadrant for branding and headline overlay",
  "overlay-top-right": "leave clean negative space in the upper-right quadrant for branding and headline overlay",
  "overlay-lower-left": "leave clean negative space in the lower-left quadrant for headline overlay",
  "overlay-lower-center": "leave clean negative space in the lower-center area for headline overlay",
};

const DISPLAY_TITLE_OVERRIDES = {
  US_FED_RATE_DECISION: "FED RATE DECISION",
  US_FED_STATEMENT: "FOMC STATEMENT",
  US_POWELL_SPEECH: "FED PRESS CONFERENCE",
  US_FOMC_MINUTES: "FOMC MINUTES",
  US_BEIGE_BOOK: "FED BEIGE BOOK",
  US_JACKSON_HOLE: "JACKSON HOLE SYMPOSIUM",
  US_CPI_MOM: "US CPI INFLATION",
  US_CPI_YOY: "US CPI INFLATION",
  US_CPI_GENERIC: "US CPI INFLATION",
  US_CORE_CPI_MOM: "CORE CPI INFLATION",
  US_CORE_CPI_YOY: "CORE CPI INFLATION",
  US_PPI_MOM: "US PPI INFLATION",
  US_PPI_YOY: "US PPI INFLATION",
  US_CORE_PCE_MOM: "CORE PCE INFLATION",
  US_CORE_PCE_YOY: "CORE PCE INFLATION",
  US_NFP: "US NONFARM PAYROLLS",
  US_UNEMPLOYMENT_RATE: "US UNEMPLOYMENT RATE",
  US_ADP: "US ADP EMPLOYMENT",
  US_ADP_EMPLOYMENT: "US ADP EMPLOYMENT",
  US_INITIAL_JOBLESS_CLAIMS: "US JOBLESS CLAIMS",
  US_CONTINUING_JOBLESS_CLAIMS: "US CONTINUING CLAIMS",
  US_GDP_QOQ: "US GDP GROWTH",
  US_RETAIL_SALES: "US RETAIL SALES",
  US_CONSUMER_CONFIDENCE: "US CONSUMER CONFIDENCE",
  US_MICHIGAN_SENTIMENT: "MICHIGAN SENTIMENT",
  US_ISM_MANUFACTURING: "ISM Manufacturing",
  US_ISM_SERVICES: "US ISM Services",
  US_PMI_MANUFACTURING: "US Manufacturing PMI",
  US_PMI_SERVICES: "US Services PMI",
  ECB_RATE_DECISION: "ECB Rate Decision",
  ECB_LAGARDE_SPEECH: "ECB Press Conference",
  BOE_RATE_DECISION: "BoE Rate Decision",
  BOE_BAILEY_SPEECH: "BoE Press Conference",
  BOJ_RATE_DECISION: "BoJ Rate Decision",
  BOJ_UEDA_SPEECH: "BoJ Press Conference",
};

module.exports = {
  REALISM_DIRECTIVES,
  NEGATIVE_PROMPT,
  FORBIDDEN_PROMPT_TERMS,
  OVERLAY_PLACEMENTS,
  DISPLAY_TITLE_OVERRIDES,
  TEXT_FREE_DIRECTIVE,
};
