/** @type {import("./types").AssetHubConfig} */
export const btcAssetConfig = {
  id: "btc",
  slug: "btc",
  path: "/btc",
  name: "البيتكوين",
  nameEn: "Bitcoin",
  symbol: "BTC",
  tradingViewSymbol: "BINANCE:BTCUSDT",
  chartSymbol: "BTCUSDT",
  chartExchange: "BINANCE",
  pricePairLabel: "BTC / USDT",
  category: "crypto",
  categoryLabel: "العملات الرقمية",
  categoryPath: "/crypto",
  hero: {
    badge: "Asset Hub — Bitcoin",
    title: "البيتكوين (BTC)",
    description:
      "مركز معلومات متكامل للبيتكوين: السعر المباشر، الشارت، ملخص السوق، آخر الأخبار والتحليلات، والخدمات المرتبطة — ضمن HasaN CharT World.",
    accentRgb: "247,147,26",
  },
  description: {
    marketSummary:
      "البيتكوين يقود سوق العملات الرقمية ويتحرك على مدار 24 ساعة. يتأثر السعر بالسيولة المؤسسية، أخبار التنظيم، قرارات الفيدرالي، وتدفقات ETF والتبنّي العالمي.",
    tradingHours: "24 / 7",
    platform: "Binance",
  },
  news: {
    keywords: ["bitcoin", "btc", "بيتكوين"],
    tagHref: "/news/tag/bitcoin",
    archiveLabel: "أرشيف أخبار البيتكوين",
  },
  analysis: {
    keywords: ["btc", "bitcoin", "بيتكوين", "btcusdt"],
  },
  faq: [
    {
      q: "ما هو البيتكوين (BTC)؟",
      a: "البيتكوين أول عملة رقمية لامركزية، يُتداول على مدار 24 ساعة ويُعد المرجع الرئيسي لسوق العملات الرقمية.",
    },
    {
      q: "كيف أتابع سعر البيتكوين في HasaN CharT World؟",
      a: "من خلال السعر المباشر وشارت TradingView في هذه الصفحة، أو عبر التنبيهات السعرية عند وصول BTC لمستوى محدد.",
    },
    {
      q: "هل توفر المنصة تحليلات وإشارات للبيتكوين؟",
      a: "نعم، عبر التحليلات اليومية وخدمات VIP Spot و VIP Futures وطلب تحليل مخصص لـ BTC.",
    },
    {
      q: "كيف أنشئ تنبيه سعري للبيتكوين؟",
      a: "انتقل إلى صفحة التنبيهات السعرية وأنشئ تنبيهاً لزوج BTC/USDT أو الأصل الذي تتابعه.",
    },
    {
      q: "أين أجد أخبار البيتكوين؟",
      a: "في قسم آخر أخبار BTC في هذه الصفحة، أو في أرشيف أخبار البيتكوين عبر /news/tag/bitcoin.",
    },
  ],
  relatedAssets: [
    {
      symbol: "ETH",
      name: "الإيثيريوم",
      description: "ثاني أكبر عملة رقمية — منصة العقود الذكية وطبقة Web3.",
      href: "/crypto",
    },
    {
      symbol: "XAU",
      name: "الذهب",
      description: "ملاذ آمن يتأثر أحياناً بحركة البيتكوين والدولار.",
      href: "/gold",
    },
    {
      symbol: "OIL",
      name: "النفط",
      description: "سلعة طاقة مؤثرة على المخاطرة والتضخم العالمي.",
      href: "/oil",
    },
    {
      symbol: "FX",
      name: "الفوركس",
      description: "أسواق العملات الأجنبية — ارتباط الدولار بسوق الكريبتو.",
      href: "/forex",
    },
  ],
  links: {
    internal: [
      { label: "الأسواق المالية", href: "/markets" },
      { label: "العملات الرقمية", href: "/crypto" },
      { label: "تحليل الكريبتو", href: "/crypto-analysis" },
      { label: "أخبار البيتكوين", href: "/news/tag/bitcoin" },
      { label: "التحليلات اليومية", href: "/daily-analysis" },
      { label: "طلب تحليل", href: "/analysis/request" },
      { label: "التنبيهات السعرية", href: "/price-alerts" },
      { label: "التنبيهات", href: "/alerts" },
      { label: "VIP Spot", href: "/vip-spot" },
      { label: "VIP Futures", href: "/vip-futures" },
      { label: "إدارة الحسابات", href: "/account-management" },
      { label: "التحليل الفني", href: "/technical-analysis" },
    ],
    jsonLd: [
      { name: "البيتكوين BTC", url: "/btc" },
      { name: "العملات الرقمية", url: "/crypto" },
      { name: "أخبار البيتكوين", url: "/news/tag/bitcoin" },
      { name: "التحليلات اليومية", url: "/daily-analysis" },
      { name: "طلب تحليل", url: "/analysis/request" },
      { name: "التنبيهات السعرية", url: "/price-alerts" },
      { name: "التنبيهات", url: "/alerts" },
      { name: "VIP Spot", url: "/vip-spot" },
      { name: "VIP Futures", url: "/vip-futures" },
      { name: "إدارة الحسابات", url: "/account-management" },
      { name: "الذهب", url: "/gold" },
      { name: "الفوركس", url: "/forex" },
    ],
    marketSummary: [
      { label: "سوق الكريبتو", href: "/crypto" },
      { label: "أخبار البيتكوين", href: "/news/tag/bitcoin" },
      { label: "التحليل الفني", href: "/technical-analysis" },
    ],
  },
  services: [
    {
      icon: "💎",
      title: "VIP Spot",
      description: "توصيات وتغطية احترافية لتداول البيتكوين والكريبتو في السوق الفوري (Spot).",
      href: "/vip-spot",
      cta: "استكشف VIP Spot",
    },
    {
      icon: "⚡",
      title: "VIP Futures",
      description: "تحليلات وإشارات لتداول عقود البيتكوين الآجلة مع إدارة مخاطر واضحة.",
      href: "/vip-futures",
      cta: "استكشف VIP Futures",
    },
    {
      icon: "🛡️",
      title: "إدارة الحسابات",
      description: "إدارة محافظ الكريبتو والمخاطر باحترافية ضمن خدمات HasaN CharT World.",
      href: "/account-management",
      cta: "إدارة الحسابات",
    },
  ],
  metadata: {
    title: "HasaN CharT World | البيتكوين BTC — مركز المعلومات",
    description:
      "مركز معلومات البيتكوين في HasaN CharT World: السعر المباشر، شارت TradingView، ملخص السوق، آخر أخبار وتحليلات BTC، التنبيهات السعرية وخدمات VIP.",
    keywords: [
      "HasaN CharT World",
      "البيتكوين",
      "BTC",
      "Bitcoin",
      "سعر البيتكوين",
      "شارت البيتكوين",
      "تحليل البيتكوين",
      "أخبار البيتكوين",
      "تنبيه سعر BTC",
      "العملات الرقمية",
      "VIP Spot",
      "VIP Futures",
    ],
  },
  jsonLd: {
    productName: "Bitcoin",
    alternateNames: ["BTC", "البيتكوين"],
    productCategory: "Cryptocurrency",
    itemListName: "مركز معلومات البيتكوين في HasaN CharT World",
    fragmentId: "bitcoin",
  },
  breadcrumbs: [
    { label: "الرئيسية", href: "/" },
    { label: "الأسواق المالية", href: "/markets" },
    { label: "العملات الرقمية", href: "/crypto" },
    { label: "البيتكوين", href: "/btc" },
  ],
};
