const V2_REASON_CODES = Object.freeze({
  V2_NUMERIC_MISMATCH: "V2_NUMERIC_MISMATCH",
  V2_ENTITY_MISMATCH: "V2_ENTITY_MISMATCH",
  V2_ROLE_MISMATCH: "V2_ROLE_MISMATCH",
  V2_ENTITY_ROLE_CONFLICT: "V2_ENTITY_ROLE_CONFLICT",
  V2_ATTRIBUTION_MISMATCH: "V2_ATTRIBUTION_MISMATCH",
  V2_QUOTE_MISMATCH: "V2_QUOTE_MISMATCH",
  V2_UNCERTAINTY_UPGRADE: "V2_UNCERTAINTY_UPGRADE",
  V2_UNSUPPORTED_CLAIM: "V2_UNSUPPORTED_CLAIM",
  V2_HEADLINE_BODY_MISMATCH: "V2_HEADLINE_BODY_MISMATCH",
  V2_INSUFFICIENT_EVIDENCE: "V2_INSUFFICIENT_EVIDENCE",
  V2_LOW_INFORMATION: "V2_LOW_INFORMATION",
  V2_CURATOR_SKIPPED: "V2_CURATOR_SKIPPED",
  V2_EDITORIAL_AI_FAILED: "V2_EDITORIAL_AI_FAILED",
  V2_EDITORIAL_TIMEOUT: "V2_EDITORIAL_TIMEOUT",
});

const V2_ISSUE_CODES = Object.freeze({
  NUMERIC_MISMATCH: "NUMERIC_MISMATCH",
  ENTITY_MISMATCH: "ENTITY_MISMATCH",
  ROLE_MISMATCH: "ROLE_MISMATCH",
  ENTITY_ROLE_CONFLICT: "ENTITY_ROLE_CONFLICT",
  ATTRIBUTION_MISMATCH: "ATTRIBUTION_MISMATCH",
  QUOTE_MISMATCH: "QUOTE_MISMATCH",
  UNCERTAINTY_UPGRADED: "UNCERTAINTY_UPGRADED",
  UNSUPPORTED_CLAIM: "UNSUPPORTED_CLAIM",
  HEADLINE_BODY_MISMATCH: "HEADLINE_BODY_MISMATCH",
  INSUFFICIENT_EVIDENCE: "INSUFFICIENT_EVIDENCE",
  LOW_INFORMATION: "LOW_INFORMATION",
  MALFORMED_OUTPUT: "MALFORMED_OUTPUT",
});

const ISSUE_TO_V2_REASON = Object.freeze({
  [V2_ISSUE_CODES.NUMERIC_MISMATCH]: V2_REASON_CODES.V2_NUMERIC_MISMATCH,
  [V2_ISSUE_CODES.ENTITY_MISMATCH]: V2_REASON_CODES.V2_ENTITY_MISMATCH,
  [V2_ISSUE_CODES.ROLE_MISMATCH]: V2_REASON_CODES.V2_ROLE_MISMATCH,
  [V2_ISSUE_CODES.ENTITY_ROLE_CONFLICT]: V2_REASON_CODES.V2_ENTITY_ROLE_CONFLICT,
  [V2_ISSUE_CODES.ATTRIBUTION_MISMATCH]: V2_REASON_CODES.V2_ATTRIBUTION_MISMATCH,
  [V2_ISSUE_CODES.QUOTE_MISMATCH]: V2_REASON_CODES.V2_QUOTE_MISMATCH,
  [V2_ISSUE_CODES.UNCERTAINTY_UPGRADED]: V2_REASON_CODES.V2_UNCERTAINTY_UPGRADE,
  [V2_ISSUE_CODES.UNSUPPORTED_CLAIM]: V2_REASON_CODES.V2_UNSUPPORTED_CLAIM,
  [V2_ISSUE_CODES.HEADLINE_BODY_MISMATCH]: V2_REASON_CODES.V2_HEADLINE_BODY_MISMATCH,
  [V2_ISSUE_CODES.INSUFFICIENT_EVIDENCE]: V2_REASON_CODES.V2_INSUFFICIENT_EVIDENCE,
  [V2_ISSUE_CODES.LOW_INFORMATION]: V2_REASON_CODES.V2_LOW_INFORMATION,
});

module.exports = {
  V2_REASON_CODES,
  V2_ISSUE_CODES,
  ISSUE_TO_V2_REASON,
};
