const NEWS_EVENTS = {
  CANDIDATE_RECEIVED: "NEWS_CANDIDATE_RECEIVED",
  EVENT_NORMALIZED: "NEWS_EVENT_NORMALIZED",
  LOCK_ACQUIRED: "NEWS_EVENT_LOCK_ACQUIRED",
  DUPLICATE_BLOCKED: "NEWS_DUPLICATE_BLOCKED",
  RAW_FALLBACK_BLOCKED: "NEWS_RAW_FALLBACK_BLOCKED",
  COPY_SIMILARITY_BLOCKED: "NEWS_COPY_SIMILARITY_BLOCKED",
  FACT_INTEGRITY_BLOCKED: "NEWS_FACT_INTEGRITY_BLOCKED",
  EDITORIAL_INVALID: "NEWS_EDITORIAL_OUTPUT_INVALID",
  PUBLICATION_ALLOWED: "NEWS_PUBLICATION_ALLOWED",
  PUBLICATION_SUCCESS: "NEWS_PUBLICATION_SUCCESS",
  PUBLICATION_FAILED: "NEWS_PUBLICATION_FAILED",
};

function logNewsEvent(event, payload = {}) {
  const safe = { event, ...payload };
  console.log(event, JSON.stringify(safe));
}

module.exports = {
  NEWS_EVENTS,
  logNewsEvent,
};
