export const ANALYTICS_EVENTS = Object.freeze({
  REGISTRATION_STARTED: "registration_started",
  REGISTRATION_COMPLETED: "registration_completed",
  LOGIN_COMPLETED: "login_completed",
  SUBSCRIPTION_VIEWED: "subscription_viewed",
  SUBSCRIPTION_CTA_CLICKED: "subscription_cta_clicked",
  SUBSCRIPTION_PLAN_SELECTED: "subscription_plan_selected",
  PAYMENT_PROOF_STARTED: "payment_proof_started",
  PAYMENT_PROOF_SUBMITTED: "payment_proof_submitted",
  TELEGRAM_CTA_CLICKED: "telegram_cta_clicked",
  NEWS_ARTICLE_OPENED: "news_article_opened",
  VIP_SERVICE_VIEWED: "vip_service_viewed",
  VIP_SUBSCRIPTION_CTA_CLICKED: "vip_subscription_cta_clicked",
  PRICE_ALERT_CTA_CLICKED: "price_alert_cta_clicked",
  PRICE_ALERT_CREATED: "price_alert_created",
});
