/**
 * Semantic class bundles for the shared Design System.
 * Pair with app/design-system/design-system-theme.css tokens.
 */

export const ui = {
  surface: "ui-surface rounded-2xl shadow-sm backdrop-blur-sm",
  surfaceMuted: "ui-surface-muted rounded-xl",
  textStrong: "ui-text-strong",
  textMuted: "ui-text-muted",
  textSubtle: "ui-text-subtle",
  input:
    "ui-input h-10 w-full min-w-0 rounded-xl px-3 py-2 text-sm outline-none transition",
  select:
    "ui-input h-10 w-full min-w-0 appearance-none rounded-xl px-3 py-2 text-sm outline-none transition",
  btn: "ui-btn",
  btnPrimary: "ui-btn ui-btn--primary px-4 py-2.5 text-sm",
  btnSecondary: "ui-btn ui-btn--secondary px-4 py-2.5 text-sm",
  btnGhost: "ui-btn ui-btn--ghost px-4 py-2.5 text-sm",
  btnDanger: "ui-btn ui-btn--danger px-4 py-2.5 text-sm",
  card: "ui-card p-5",
  badgeNeutral: "ui-badge ui-badge--neutral",
  badgePositive: "ui-badge ui-badge--positive",
  badgeNegative: "ui-badge ui-badge--negative",
  badgeWarning: "ui-badge ui-badge--warning",
  alertInfo: "ui-alert ui-alert--info",
  alertSuccess: "ui-alert ui-alert--success",
  alertWarning: "ui-alert ui-alert--warning",
  alertError: "ui-alert ui-alert--error",
  portalMenu:
    "ui-portal-menu max-h-56 overflow-y-auto overscroll-contain rounded-xl py-1",
  portalOptionActive: "ui-portal-option--active",
  portalOptionIdle: "ui-portal-option--idle",
  modalScrim:
    "ui-modal-scrim pointer-events-auto fixed inset-0 z-[200] flex items-center justify-center px-5",
  modalPanel: "ui-modal-panel w-full max-w-md p-8 text-center",
  pageShell: "ui-page-shell min-w-0",
  pageHeader: "ui-page-header",
  pageHeaderTitle: "ui-page-header__title",
  pageHeaderSubtitle: "ui-page-header__subtitle",
  empty: "ui-empty",
  loading: "ui-loading",
  error: "ui-error",
  focusRing:
    "focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--ui-focus-ring)]",
  publicSeoPage: "ui-public-seo-page public-seo-page",
  publicSeoHero: "ui-public-seo-hero public-seo-hero",
  publicSeoCard: "ui-public-seo-card public-seo-card",
  publicSeoCardCompact:
    "ui-public-seo-card ui-public-seo-card--compact public-seo-card",
  publicSeoCardFaq:
    "ui-public-seo-card ui-public-seo-card--faq group public-seo-card",
  publicSeoSection: "ui-public-seo-section",
  publicSeoInfoCard: "ui-public-seo-info-card group",
  glass5: "ui-glass-5",
  glass10: "ui-glass-10",
  glass15: "ui-glass-15",
  glass25: "ui-glass-25",
  glass045: "ui-glass-045",
  glass04: "ui-glass-04",
  glass06: "ui-glass-06",
  inputDark: "ui-input-dark",
  pageDark: "ui-page-dark",
  textOnEmerald: "ui-text-on-emerald",
  shellMenuItem: "site-shell-menu-item",
  shellMenuItemDesktop: "site-shell-menu-item site-shell-menu-item--desktop",
  shellMenuIcon: "site-shell-menu-item__icon",
  shellMenuLabel: "site-shell-menu-item__label",
  shellMenuGroup: "site-shell-menu-group-toggle",
  shellMenuGroupIcon: "site-shell-menu-group-toggle__icon",
  shellMenuGroupChevron: "site-shell-menu-group-toggle__chevron",
  shellMenuGroupChevronOpen:
    "site-shell-menu-group-toggle__chevron site-shell-menu-group-toggle__chevron--open",
  shellDivider: "site-shell-divider",
  shellAdminLink: "site-shell-admin-link site-shell-menu-item--desktop",
  shellAdminLinkMobile: "site-shell-admin-link",
  shellBadgeCount: "site-shell-badge-count",
  shellNotice: "site-shell-notice",
  shellNoticeTitle: "site-shell-notice__title",
  shellNoticeBody: "site-shell-notice__body",
  shellNoticeBtn: "site-shell-notice__btn",
  shellNoticeClose: "site-shell-notice__close",
  shellContactPanel: "site-shell-contact-panel",
  shellContactLink: "site-shell-contact-link",
  shellContactBadge: "site-shell-contact-link__badge",
  shellContactMuted: "site-shell-contact-link__muted",
  shellUserEmail: "site-shell-user-email truncate",
  shellLoginBtn: "site-shell-login-btn",
  shellAvatar: "site-shell-avatar",
  shellSkeleton: "site-shell-skeleton",
  shellLogoutBtn: "site-shell-logout-btn",
  shellGridOverlay: "site-shell-grid-overlay",
  shellHeaderMenuBtn: "site-shell-header-menu-btn",
  shellNoticeProgressTrack:
    "site-shell-notice__progress-track absolute bottom-0 left-0 h-1 w-full",
  shellNoticeProgressValue: "site-shell-notice__progress-value",
  bootstrapScreen:
    "ui-bootstrap-screen fixed inset-0 z-[9998] flex min-h-screen items-center justify-center overflow-hidden",
  bootstrapBg: "ui-bootstrap-screen__bg pointer-events-none absolute inset-0",
  bootstrapGrid: "ui-bootstrap-grid",
  bootstrapContent:
    "ui-bootstrap-content relative z-10 w-full max-w-xl px-5 sm:px-6",
  bootstrapSurface:
    "ui-bootstrap-surface ui-badge-panel relative overflow-hidden rounded-[34px] p-8 text-center backdrop-blur-2xl md:p-10",
  bootstrapOrb: "ui-bootstrap-orb pointer-events-none absolute",
  bootstrapOrbPrimary:
    "ui-bootstrap-orb ui-bootstrap-orb--primary top-[10%] right-[7%] h-72 w-72",
  bootstrapOrbSecondary:
    "ui-bootstrap-orb ui-bootstrap-orb--secondary bottom-[8%] left-[5%] h-56 w-56",
  bootstrapTitle:
    "ui-bootstrap-title relative z-10 text-2xl font-black leading-tight tracking-tight md:text-[1.75rem]",
  bootstrapSubtitle:
    "ui-bootstrap-subtitle relative z-10 mt-3 text-sm leading-7 md:text-base",
  bootstrapTagline:
    "ui-bootstrap-tagline mt-5 text-center text-[11px] font-bold uppercase tracking-[0.24em]",
  bootstrapLogo:
    "ui-bootstrap-logo relative z-10 grid h-24 w-24 place-items-center overflow-hidden rounded-[28px]",
  bootstrapLogoGlow: "ui-bootstrap-logo__glow",
  bootstrapLogoShine: "ui-bootstrap-logo__shine",
  bootstrapBarShort: "ui-bootstrap-bar ui-bootstrap-bar--short",
  bootstrapBarMid: "ui-bootstrap-bar ui-bootstrap-bar--mid",
  bootstrapBarTall: "ui-bootstrap-bar ui-bootstrap-bar--tall",
  bootstrapRing:
    "ui-bootstrap-ring pointer-events-none absolute inset-0 rounded-[32px]",
  bootstrapRingInner:
    "ui-bootstrap-ring__inner absolute inset-[3px] rounded-[29px]",
  bootstrapRingGlow:
    "ui-bootstrap-ring__glow pointer-events-none absolute inset-[-10px] rounded-[36px]",
  bootstrapDot: "ui-bootstrap-dot",
  bootstrapDotDelay1: "ui-bootstrap-dot ui-bootstrap-dot--delay-1",
  bootstrapDotDelay2: "ui-bootstrap-dot ui-bootstrap-dot--delay-2",
  bootstrapExit: "ui-bootstrap-screen--exit",
  bootstrapCardGlow:
    "ui-bootstrap-card-glow pointer-events-none absolute inset-0",
  bootstrapCardLine:
    "ui-bootstrap-card-line pointer-events-none absolute inset-x-8 top-0",
  homeRoot: "site-home-root",
  homeHeroOverlay: "site-home-hero-overlay",
  homeFormPanel: "site-home-form-panel",
  homeFormTitle: "site-home-form-title",
  homeFormHint: "site-home-form-hint",
  homeFormCooldown: "site-home-form-cooldown",
  homeFormLink: "site-home-form-link",
  homeFormChip: "site-home-form-chip",
  homeFormChipActive: "site-home-form-chip site-home-form-chip--active",
  homeServiceCard: "site-home-service-card",
  homeServiceTitle: "site-home-service-title",
  homeServiceText: "site-home-service-text",
  homeServiceCta: "site-home-service-cta",
  homeNotice: "site-home-notice",
  homeSkeletonCard:
    "site-home-skeleton-card site-price-card site-price-card--tv",
  homeChartLoading: "site-home-chart-loading site-live-chart-panel glassPanel",
  publicSeoTitle: "ui-public-seo-title",
  publicSeoTitleSection: "ui-public-seo-title ui-public-seo-title--section",
  publicSeoTitleCard: "ui-public-seo-title ui-public-seo-title--card",
  publicSeoSubtitle: "ui-public-seo-subtitle",
  publicSeoBody: "ui-public-seo-body",
  publicSeoBodyLg: "ui-public-seo-body ui-public-seo-body--lg",
  publicSeoLinkChip: "ui-public-seo-link-chip",
  publicSeoCtaPrimary: "ui-public-seo-cta-primary",
  publicSeoCtaSecondary: "ui-public-seo-cta-secondary",
  publicSeoCtaBand: "ui-public-seo-cta-band",
  publicSeoCtaBandCompact:
    "ui-public-seo-cta-band ui-public-seo-cta-band--compact",
  publicSeoCtaBandFull: "ui-public-seo-cta-band ui-public-seo-cta-band--full",
  publicSeoListItem: "ui-public-seo-list-item",
  publicSeoContactLink: "ui-public-seo-contact-link",
  publicSeoFaqSummary: "ui-public-seo-faq-summary",
  publicSeoBadge: "ui-public-seo-badge",
  publicSeoGuestBanner: "ui-public-seo-guest-banner",
  publicSeoGuestBannerText: "ui-public-seo-guest-banner__text",
};

export const UNSAFE_UI_PATTERNS = [
  /\bbg-white\b/,
  /\btext-white\b/,
  /\btext-black\b/,
  /\bdark:bg-/,
  /\bdark:text-/,
  /\btext-slate-\d+/,
  /\bborder-slate-/,
  /\bbg-gradient-/,
  /\bfrom-[\w[\]./-]+/,
  /\bvia-[\w[\]./-]+/,
  /\bto-[\w[\]./-]+/,
  /\bborder-white/,
  /\btext-cyan-\d+/,
  /\bborder-cyan-/,
  /\bbg-cyan-/,
  /\btext-blue-\d+/,
  /\bbg-blue-/,
  /\bborder-blue-/,
  /\bbg-emerald-/,
  /\bborder-emerald-/,
  /\btext-emerald-/,
  /\bbg-red-/,
  /\bborder-red-/,
  /\btext-red-/,
  /\bbg-amber-/,
  /\bborder-amber-/,
  /\btext-amber-/,
  /\bring-cyan-/,
  /\bshadow-emerald-/,
  /\bdark:hidden\b/,
  /\bdark:block\b/,
  /\bbg-\[#/,
  /\bbg-black/,
  /(?<![-\w])#[0-9a-fA-F]{3,8}\b/,
  /<select[\s>]/,
  /\[class\*="/,
  /style=\{\{[^}]*(?:(?<![-\w])color\s*:|(?<![-\w])background\s*:|border(?:Color|Style)?\s*:|boxShadow\s*:|textShadow\s*:|WebkitTextFillColor\s*:)/,
];

export const FINANCIAL_CHART_ALLOWLIST = [
  "TradingView",
  "tradingview",
  "lightweight-charts",
  "chart-container",
];

export const LEGACY_UI_PATH_PREFIXES = [
  "app/components/order-book/",
  "app/(app)/order-book/",
  "app/components/AppModal.js",
  "app/(app)/admin/",
  "app/components/iam/",
  "app/components/asset-hub/",
  "app/components/market/",
];
