const PHASE2_EVENTS = {
  ECONOMIC_EDITOR_STARTED: "ECONOMIC_EDITOR_STARTED",
  ECONOMIC_EDITOR_COMPLETED: "ECONOMIC_EDITOR_COMPLETED",
  ECONOMIC_INTERPRETATION_DETERMINISTIC: "ECONOMIC_INTERPRETATION_DETERMINISTIC",
  ECONOMIC_AI_EDITOR_USED: "ECONOMIC_AI_EDITOR_USED",
  ECONOMIC_AI_EDITOR_SKIPPED: "ECONOMIC_AI_EDITOR_SKIPPED",
  EVENT_FAMILY_WAITING: "EVENT_FAMILY_WAITING",
  EVENT_FAMILY_MERGED: "EVENT_FAMILY_MERGED",
  EVENT_FAMILY_WINDOW_EXPIRED: "EVENT_FAMILY_WINDOW_EXPIRED",
  QUALITY_GATE_PASSED: "QUALITY_GATE_PASSED",
  QUALITY_GATE_BLOCKED: "QUALITY_GATE_BLOCKED",
  HALLUCINATED_NUMERIC_TOKEN: "HALLUCINATED_NUMERIC_TOKEN",
  IMAGE_REQUIRED: "IMAGE_REQUIRED",
  IMAGE_SELECTED: "IMAGE_SELECTED",
  IMAGE_FALLBACK_USED: "IMAGE_FALLBACK_USED",
  IMAGE_REQUIRED_UNAVAILABLE: "IMAGE_REQUIRED_UNAVAILABLE",
};

function logPhase2Event(event, payload = {}) {
  console.log(event, JSON.stringify({ event, ...payload }));
}

module.exports = {
  PHASE2_EVENTS,
  logPhase2Event,
};
