import { evaluateAlertRules } from "./alerts.mjs";

const RCA_TEMPLATES = Object.freeze({
  health: "Service health endpoint returned non-200 or readiness != ready. Check Railway logs, env vars, and worker connectivity.",
  auth: "Authentication pipeline failed. Verify Supabase Auth, cookie sync (/api/auth/sync-session), and E2E credentials.",
  orderBook: "Market depth snapshot did not reach connected exchanges within warmup window. Check MarketDepthHub WS to Binance/Bybit/OKX.",
  visual: "UI differed from baseline beyond tolerance. Review diff images; update baselines if intentional.",
  worker: "Background worker unavailable. Check Railway worker service, Redis queue, and OPENAI_API_KEY.",
  latency: "Page load or LCP exceeded SLO threshold. Profile slow routes and optimize critical path.",
  release: "Release Gate returned NO-GO. Resolve all P0/P1 blocking issues before deploy.",
});

export function buildIncidentReport(qa, alerts, releaseGate, slo) {
  const fired = alerts.rules.filter((r) => r.fired);
  const gateVerdict = releaseGate?.verdict || "UNKNOWN";
  const severity =
    fired.some((r) => r.severity === "critical") || gateVerdict === "NO-GO"
      ? "SEV-1"
      : fired.some((r) => r.severity === "high")
        ? "SEV-2"
        : fired.length
          ? "SEV-3"
          : "NONE";

  const timeline = buildTimeline(qa, fired, releaseGate);

  const incidents = fired.map((rule, i) => ({
    id: `INC-${Date.now()}-${i + 1}`,
    alertRuleId: rule.id,
    severity: rule.severity,
    title: rule.condition,
    status: "open",
    runbook: `docs/runbooks/${rule.runbook}`,
    rootCauseTemplate: pickRcaTemplate(rule.id),
    suggestedActions: pickActions(rule.id),
    openedAt: new Date().toISOString(),
  }));

  if (gateVerdict === "NO-GO" && !incidents.some((i) => i.alertRuleId === "AR-010")) {
    incidents.push({
      id: `INC-GATE-${Date.now()}`,
      alertRuleId: "AR-010",
      severity: "critical",
      title: "Release Gate NO-GO",
      status: "open",
      runbook: "docs/runbooks/release-blocked.md",
      rootCauseTemplate: RCA_TEMPLATES.release,
      suggestedActions: ["Review release-gate.json blockingIssues", "Fix P0/P1 issues", "Re-run smoke"],
      openedAt: new Date().toISOString(),
    });
  }

  return {
    generatedAt: new Date().toISOString(),
    autoGenerated: true,
    severity,
    incidentCount: incidents.length,
    incidents,
    timeline,
    sloImpact: slo.overallStatus,
    releaseGateVerdict: gateVerdict,
    status: incidents.length === 0 ? "clear" : severity === "SEV-1" ? "critical" : "warning",
  };
}

function buildTimeline(qa, fired, releaseGate) {
  const events = [];
  if (qa.available && qa.smoke?.metadata) {
    events.push({
      ts: qa.smoke.metadata.startedAt,
      type: "smoke-started",
      message: `Smoke test started (${qa.runId})`,
    });
    events.push({
      ts: qa.smoke.metadata.finishedAt,
      type: "smoke-finished",
      message: `Smoke finished — verdict ${qa.smoke.verdict}`,
    });
  }
  if (releaseGate) {
    events.push({
      ts: releaseGate.generatedAt,
      type: "release-gate",
      message: `Release Gate: ${releaseGate.verdict} (score ${releaseGate.score})`,
    });
  }
  for (const rule of fired) {
    events.push({
      ts: rule.evaluatedAt,
      type: "alert-fired",
      message: `[${rule.severity}] ${rule.id}: ${rule.condition}`,
    });
  }
  events.push({
    ts: new Date().toISOString(),
    type: "ops-report",
    message: "Enterprise Operations report generated",
  });
  return events.sort((a, b) => String(a.ts).localeCompare(String(b.ts)));
}

function pickRcaTemplate(ruleId) {
  const map = {
    "AR-001": RCA_TEMPLATES.health,
    "AR-002": RCA_TEMPLATES.auth,
    "AR-003": RCA_TEMPLATES.orderBook,
    "AR-004": RCA_TEMPLATES.visual,
    "AR-008": RCA_TEMPLATES.worker,
    "AR-006": RCA_TEMPLATES.latency,
    "AR-010": RCA_TEMPLATES.release,
  };
  return map[ruleId] || "Investigate alert condition and correlate with smoke step logs.";
}

function pickActions(ruleId) {
  const map = {
    "AR-001": ["Check /api/health", "Verify Railway service status", "Review worker logs"],
    "AR-002": ["Verify Supabase Auth config", "Check E2E credentials", "Test /api/auth/login manually"],
    "AR-003": ["Wait 15-20s for order book bootstrap", "Check exchange WS connectivity", "Review market-depth-hub logs"],
    "AR-004": ["Review diff PNGs", "Update baselines if UI change intentional"],
    "AR-010": ["Open release-gate.json", "Fix blocking issues", "Re-run smoke:staging"],
  };
  return map[ruleId] || ["Consult runbook", "Escalate to on-call if SEV-1"];
}

export { evaluateAlertRules };
