-- Market flow history (Phase 3A schema only — server-managed, not applied yet).
-- Stores 1-minute executed flow buckets and large trade events for /order-book history.

-- ---------------------------------------------------------------------------
-- A. market_flow_buckets
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.market_flow_buckets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol text NOT NULL,
  exchange_scope text NOT NULL,
  bucket_start timestamptz NOT NULL,
  bucket_seconds integer NOT NULL DEFAULT 60,
  buy_notional numeric(20, 4) NOT NULL DEFAULT 0,
  sell_notional numeric(20, 4) NOT NULL DEFAULT 0,
  buy_count integer NOT NULL DEFAULT 0,
  sell_count integer NOT NULL DEFAULT 0,
  max_trade_notional numeric(20, 4) NOT NULL DEFAULT 0,
  large_25k_count integer NOT NULL DEFAULT 0,
  large_50k_count integer NOT NULL DEFAULT 0,
  large_100k_count integer NOT NULL DEFAULT 0,
  large_250k_count integer NOT NULL DEFAULT 0,
  large_500k_count integer NOT NULL DEFAULT 0,
  large_1m_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.market_flow_buckets IS
  'Server-managed 1-minute executed flow buckets for /order-book historical windows. Written by service_role only.';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_flow_buckets_symbol_scope_bucket_key'
      AND conrelid = 'public.market_flow_buckets'::regclass
  ) THEN
    ALTER TABLE public.market_flow_buckets
      ADD CONSTRAINT market_flow_buckets_symbol_scope_bucket_key
      UNIQUE (symbol, exchange_scope, bucket_start);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_flow_buckets_exchange_scope_check'
      AND conrelid = 'public.market_flow_buckets'::regclass
  ) THEN
    ALTER TABLE public.market_flow_buckets
      ADD CONSTRAINT market_flow_buckets_exchange_scope_check
      CHECK (exchange_scope IN ('aggregated', 'okx', 'binance', 'bybit'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_flow_buckets_bucket_seconds_check'
      AND conrelid = 'public.market_flow_buckets'::regclass
  ) THEN
    ALTER TABLE public.market_flow_buckets
      ADD CONSTRAINT market_flow_buckets_bucket_seconds_check
      CHECK (bucket_seconds = 60);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_flow_buckets_counts_nonneg_check'
      AND conrelid = 'public.market_flow_buckets'::regclass
  ) THEN
    ALTER TABLE public.market_flow_buckets
      ADD CONSTRAINT market_flow_buckets_counts_nonneg_check
      CHECK (
        buy_count >= 0
        AND sell_count >= 0
        AND large_25k_count >= 0
        AND large_50k_count >= 0
        AND large_100k_count >= 0
        AND large_250k_count >= 0
        AND large_500k_count >= 0
        AND large_1m_count >= 0
      );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_flow_buckets_notionals_nonneg_check'
      AND conrelid = 'public.market_flow_buckets'::regclass
  ) THEN
    ALTER TABLE public.market_flow_buckets
      ADD CONSTRAINT market_flow_buckets_notionals_nonneg_check
      CHECK (
        buy_notional >= 0
        AND sell_notional >= 0
        AND max_trade_notional >= 0
      );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS market_flow_buckets_symbol_scope_bucket_start_idx
  ON public.market_flow_buckets (symbol, exchange_scope, bucket_start DESC);

CREATE INDEX IF NOT EXISTS market_flow_buckets_bucket_start_idx
  ON public.market_flow_buckets (bucket_start DESC);

CREATE OR REPLACE FUNCTION public.set_market_flow_buckets_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS market_flow_buckets_set_updated_at ON public.market_flow_buckets;

CREATE TRIGGER market_flow_buckets_set_updated_at
BEFORE UPDATE ON public.market_flow_buckets
FOR EACH ROW
EXECUTE FUNCTION public.set_market_flow_buckets_updated_at();

ALTER TABLE public.market_flow_buckets ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.market_flow_buckets FROM anon, authenticated;

GRANT ALL ON public.market_flow_buckets TO service_role;

-- ---------------------------------------------------------------------------
-- B. market_large_trades
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.market_large_trades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trade_key text NOT NULL,
  symbol text NOT NULL,
  exchange text NOT NULL,
  ts timestamptz NOT NULL,
  side text NOT NULL,
  price numeric(20, 8) NOT NULL,
  quantity numeric(20, 8) NOT NULL,
  notional numeric(20, 4) NOT NULL,
  threshold_band integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.market_large_trades IS
  'Server-managed large executed trade events (>= $25K). Written by service_role only.';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_large_trades_trade_key_key'
      AND conrelid = 'public.market_large_trades'::regclass
  ) THEN
    ALTER TABLE public.market_large_trades
      ADD CONSTRAINT market_large_trades_trade_key_key UNIQUE (trade_key);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_large_trades_exchange_check'
      AND conrelid = 'public.market_large_trades'::regclass
  ) THEN
    ALTER TABLE public.market_large_trades
      ADD CONSTRAINT market_large_trades_exchange_check
      CHECK (exchange IN ('okx', 'binance', 'bybit'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_large_trades_side_check'
      AND conrelid = 'public.market_large_trades'::regclass
  ) THEN
    ALTER TABLE public.market_large_trades
      ADD CONSTRAINT market_large_trades_side_check
      CHECK (side IN ('buy', 'sell'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_large_trades_threshold_band_check'
      AND conrelid = 'public.market_large_trades'::regclass
  ) THEN
    ALTER TABLE public.market_large_trades
      ADD CONSTRAINT market_large_trades_threshold_band_check
      CHECK (threshold_band IN (25000, 50000, 100000, 250000, 500000, 1000000));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_large_trades_notional_min_check'
      AND conrelid = 'public.market_large_trades'::regclass
  ) THEN
    ALTER TABLE public.market_large_trades
      ADD CONSTRAINT market_large_trades_notional_min_check
      CHECK (notional >= 25000);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_large_trades_price_positive_check'
      AND conrelid = 'public.market_large_trades'::regclass
  ) THEN
    ALTER TABLE public.market_large_trades
      ADD CONSTRAINT market_large_trades_price_positive_check
      CHECK (price > 0);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'market_large_trades_quantity_positive_check'
      AND conrelid = 'public.market_large_trades'::regclass
  ) THEN
    ALTER TABLE public.market_large_trades
      ADD CONSTRAINT market_large_trades_quantity_positive_check
      CHECK (quantity > 0);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS market_large_trades_symbol_ts_idx
  ON public.market_large_trades (symbol, ts DESC);

CREATE INDEX IF NOT EXISTS market_large_trades_symbol_notional_idx
  ON public.market_large_trades (symbol, notional DESC);

CREATE INDEX IF NOT EXISTS market_large_trades_exchange_symbol_ts_idx
  ON public.market_large_trades (exchange, symbol, ts DESC);

ALTER TABLE public.market_large_trades ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.market_large_trades FROM anon, authenticated;

GRANT ALL ON public.market_large_trades TO service_role;
