-- Historical liquidity walls V1 — server-managed persistence tracking for /order-book.

CREATE TABLE IF NOT EXISTS public.market_liquidity_walls (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wall_key text NOT NULL,
  symbol text NOT NULL,
  exchange text NOT NULL,
  side text NOT NULL,
  price numeric(20, 8) NOT NULL,
  size numeric(20, 8) NOT NULL DEFAULT 0,
  notional numeric(20, 4) NOT NULL DEFAULT 0,
  distance_from_mid numeric(12, 6) NOT NULL DEFAULT 0,
  snapshot_time timestamptz NOT NULL,
  first_seen timestamptz NOT NULL,
  last_seen timestamptz NOT NULL,
  lifetime_seconds integer NOT NULL DEFAULT 0,
  appearance_count integer NOT NULL DEFAULT 1,
  persistence_score numeric(6, 2) NOT NULL DEFAULT 0,
  max_size numeric(20, 8) NOT NULL DEFAULT 0,
  average_size numeric(20, 8) NOT NULL DEFAULT 0,
  reappear_count integer NOT NULL DEFAULT 0,
  strongest_notional numeric(20, 4) NOT NULL DEFAULT 0,
  survived_snapshots integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.market_liquidity_walls IS
  'Server-managed historical liquidity wall persistence for /order-book. Written by service_role only.';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'market_liquidity_walls_wall_key_key'
      AND conrelid = 'public.market_liquidity_walls'::regclass
  ) THEN
    ALTER TABLE public.market_liquidity_walls
      ADD CONSTRAINT market_liquidity_walls_wall_key_key UNIQUE (wall_key);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'market_liquidity_walls_exchange_check'
      AND conrelid = 'public.market_liquidity_walls'::regclass
  ) THEN
    ALTER TABLE public.market_liquidity_walls
      ADD CONSTRAINT market_liquidity_walls_exchange_check
      CHECK (exchange IN ('okx', 'binance', 'bybit', 'aggregated'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'market_liquidity_walls_side_check'
      AND conrelid = 'public.market_liquidity_walls'::regclass
  ) THEN
    ALTER TABLE public.market_liquidity_walls
      ADD CONSTRAINT market_liquidity_walls_side_check
      CHECK (side IN ('bid', 'ask'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS market_liquidity_walls_symbol_last_seen_idx
  ON public.market_liquidity_walls (symbol, last_seen DESC);

CREATE INDEX IF NOT EXISTS market_liquidity_walls_symbol_exchange_side_idx
  ON public.market_liquidity_walls (symbol, exchange, side, last_seen DESC);

CREATE INDEX IF NOT EXISTS market_liquidity_walls_persistence_score_idx
  ON public.market_liquidity_walls (symbol, persistence_score DESC);

ALTER TABLE public.market_liquidity_walls ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.market_liquidity_walls FROM anon, authenticated;
GRANT ALL ON public.market_liquidity_walls TO service_role;

CREATE OR REPLACE FUNCTION public.set_market_liquidity_walls_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS market_liquidity_walls_updated_at ON public.market_liquidity_walls;
CREATE TRIGGER market_liquidity_walls_updated_at
  BEFORE UPDATE ON public.market_liquidity_walls
  FOR EACH ROW
  EXECUTE FUNCTION public.set_market_liquidity_walls_updated_at();
