-- Staging-only bootstrap for legacy tables that predate supabase/migrations.
-- Safe: empty tables, no production data, no secrets.
-- Apply to Staging before continuing migration push when base schema is missing.

CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY,
  email text,
  role text,
  subscription_plan text,
  subscription_status text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.price_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_email text,
  symbol text,
  target_price numeric,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.subscription_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email text,
  username text,
  plan_name text,
  category text,
  price text,
  status text,
  payment_proof text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_email text,
  title text,
  type text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.vip_signals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_type text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.admin_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  admin_id uuid,
  admin_email text,
  action text NOT NULL,
  target_table text,
  target_id text,
  details jsonb DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public.analysis_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email text,
  status text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.account_management_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid,
  email text,
  status text,
  created_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE public.profiles IS 'Staging bootstrap stub — extended by migrations.';
COMMENT ON TABLE public.subscription_requests IS 'Staging bootstrap stub — extended by migrations.';
COMMENT ON TABLE public.admin_logs IS 'Staging bootstrap stub — extended by migrations.';
